name: Build the Docker image publish to Github Packages

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  DOCKERFILE: Dockerfile

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ["", "8", "8.1"]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare lowercase image name with tag
        env:
          PHP: ${{ matrix.php_version }}
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}${PHP:+:$PHP}" >> $GITHUB_ENV

      - name: Build and load image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ${{ env.DOCKERFILE }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
